trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
  - task: UseDotNet@2
    displayName: Instalar .NET SDK
    inputs:
      packageType: sdk
      version: '10.x'

  - script: dotnet restore DevOpsLab.slnx
    displayName: Restaurar dependências

  - script: >
      dotnet build DevOpsLab.slnx
      --configuration $(buildConfiguration)
      --no-restore
    displayName: Compilar aplicação

  - script: >
      dotnet test DevOpsLab.slnx
      --configuration $(buildConfiguration)
      --no-build
      --logger trx
      --results-directory $(Agent.TempDirectory)/TestResults
    displayName: Executar testes

  - task: PublishTestResults@2
    displayName: Publicar resultado dos testes
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx'
      searchFolder: '$(Agent.TempDirectory)/TestResults'