apiVersion: v1
kind: ConfigMap

metadata:
  name: devops-api-config
  namespace: devops-lab

data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  APP_MESSAGE: "API executada pelo Kubernetes"